### ISSUE TITLE
PostCSS

### ISSUE THREAD

**Issue by chrisjames-work** [workco/marvin#10]
If you are interested, I could adapt this to use PostCSS instead of SASS (with CSS import and CSS Next plugins, so you don't lose any of the things that make SASS great).

Let me know what you think?

**Comment by Stanko** [comment]
Hey, that would be awesome! 

I was thinking of keeping both things and making a installer which would let you choose. What do you think, any ideas on that?

**Comment by chrisjames-work** [comment]
Yeah that would be ideal, I think. Are you thinking of turning this project into a generator?

**Comment by Stanko** [comment]
Yeah, something like that. Basically a way to choose between features (sagas/thunk, universal, i18n...)

**Comment by Stanko** [comment]
https://github.com/workco/marvin/pull/65
