### ISSUE TITLE
Migrate to React Router 4.x

### ISSUE THREAD

**Issue by Stanko** [workco/marvin#21]
React Router 4.x introduced brand new API, so we need to investigate and migrate to it.

https://github.com/ReactTraining/react-router/tree/v4.0.0-beta.8#why-a-major-version-bump

**Comment by benderr** [comment]
What do you think about connect react-router with redux? Library [react-router-redux](https://github.com/ReactTraining/react-router/tree/master/packages/react-router-redux) is betta, but I found [connected-react-router](https://github.com/supasate/connected-react-router) and use in my projects, сan I use it?

**Comment by Stanko** [comment]
Hello, 
React Router 4 has it's own `withRouter` decorator, which can be used in most of the cases. https://reacttraining.com/react-router/web/guides/redux-integration

For now, I would leave deeper integration with `react-router-redux` or `connected-react-router` out of the boilerplate, as I'm afraid it could become bloated.

**Comment by shams-ali** [comment]
Hello, I made a pull request for this :)

**Comment by Stanko** [comment]
Awesome stuff! I'm going to merge it right away.

Related PR: https://github.com/workco/marvin/pull/29
