### ISSUE TITLE
Universal rendering

### ISSUE THREAD

**Issue by Stanko** [workco/marvin#22]
Universal rendering is WIP, still needs to be polished.

**Comment by jsbUSMC** [comment]
How do you plan on implementing this? I was looking at another project, and their implementation of SSR is to use react-helmet to add meta and other content to the `<head>` tag, and the `renderToString()` method from ReactDOMServer. I wouldn't mind helping out

**Comment by Stanko** [comment]
Hello, @jsbUSMC, 
I'll try to give a short overview how am I going to do it. But handling meta data won't be a part of the boilerplate. Although, `react-helmet` is a good way to do it, I've used it on a couple of projects so far. Doesn't really matter what you use, if universal part is done right.

Anyway, we'll use express, react router and react dom's `renderToString`method . I already did it for react router v3, but I'm upgrading it to support v4 (which actually made things a little easier). Harder part is getting the async data, store them in the reducer and then render everything on the server. Development process is also slightly more complicated.

Flow goes something like this:

- request hits express server
- [matchRoute](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/matchPath.md) resolves the route along with it's params
- we get async data and store it in redux reducer (optional)
- redux data is hydrated (converted to string to be returned to client) (optional)
- resolved route is rendered on the server using `renderToString` and returned as html
- client gets the response 
- clients loads the application (loads hydrated state if any) and hooks on to the server rendered html

Hope that helps!

**Comment by Stanko** [comment]
Pull request: https://github.com/workco/marvin/pull/31

At the end we might end adding `react-helmet` to the boilerplate, still TBD.

**Comment by andrewmartin** [comment]
@Stanko 

Not to reopen any can of worms here, but any idea why my `componentDidMount` hook isn't properly fetching the data? I'm basically not seeing any `async` data in the source when I view `localhost:8080`, but when I load the page, it does the AJAX call and fetches appropriately. Just making sure this is, in fact, the correct place to put that hook?

**Comment by Stanko** [comment]
Hello @andrewmartin,
That is the way it supposed to work atm. `componentDidMount` is not triggered on the server. 

To fetch async data on the server you need to add it here - https://github.com/workco/marvin/blob/master/source/js/server.js

Once route is resolved, you need to make your async requests, wait for data, pass it to the store. Then you can return rendered page to the client.

Unfortunately you need to handle this on the two places. If you find more elegant solution, please share it.

Cheers!

**Comment by andrewmartin** [comment]
Thanks man! Do you have any examples of doing this by chance? For some reason I had thought the server called that componentDidMount method in later versions of React on SSR. 

Thanks for your time :)

**Comment by Stanko** [comment]
You are welcome. Tbh last time I did this was with React Router v3, abd I need to do some research myself for v4. That's one of the things on my todo list :)

But what I did back then was to make a route-to-async-calls mapper

**Comment by Stanko** [comment]
You are welcome. Tbh last time I did this was with React Router v3, and I need to do some research myself for v4. That's one of the things on my todo list :)

You can do something like this

https://github.com/workco/marvin/blob/master/source/js/server.js#L24

```js
  // We already have store
  const store = configureStore();
  
  // Based on url
  if (req.url === '/') {
    // Fetch async data
    fakeApi.getHome().then(data => {
      // On success put it in the store
      store.dispatch(getHomeDataSuccess(data));

      // And then get server html and return it
      res.status(context.status || 200).send(serverHtml);
    });
  }
```

Hope it makes sense :)

**Comment by estrattonbailey** [comment]
Hey there 👋

Randomly stumbled on this repo and was exploring the SSR pattern when I saw this issue. Without being too nosy, just wanted to shoot you a [link to a thread](https://github.com/ReactTraining/react-router/issues/4407) I've been following for some time now about data fetching with RRv4.

My understanding right now is that since v4, it's impossible to know what components will render *prior to rendering* unless you opt to use the new static config and `StaticRouter`. Aside from that, fetching from a single top-level HOC for each route works also. For nested data dependencies, the only option is a blind render of the entire tree, fetching data, and then re-rendering. This can be costly, but tbh I haven't seen it get out of control as of yet.

Sean Matheson has done some great work with the latter idea with [async-bootstrapper](https://github.com/ctrlplusb/react-async-bootstrapper). I've also poked around it with [react-hydrate](https://github.com/estrattonbailey/react-hydrate).

Hope that's helpful! Might pull down this repo and give a go for an upcoming project, thanks for your work!! 👍

**Comment by Stanko** [comment]
Awesome, thanks @estrattonbailey I will definitively take a look.

**Comment by andrewmartin** [comment]
@estrattonbailey @Stanko 

Thanks for the both of your help :) 

I stumbled upon this today and thought maybe you'd want to take a look. I'm looking for a simple solution that doesn't require adding any additional libraries if at all possible, and judging from the way `Marvin` was built, I don't think you'd disagree :)

https://gist.github.com/ryanflorence/efbe562332d4f1cc9331202669763741

It was the first link in this thread:
https://github.com/ReactTraining/react-router/issues/4594

Thought maybe this might be helpful for reference. I'm going to be playing with this a bit today, so if I make any interesting progress I'll let you know :)

**Comment by andrewmartin** [comment]
Also, this is a really clean solution (I used this boilerplate before, and loved it).

https://github.com/CrocoDillon/universal-react-redux-boilerplate/blob/master/src/DataLoader.js

**Comment by andrewmartin** [comment]
Either of you guys get a chance to look into this by chance? This stuff is tricky. :)

**Comment by Stanko** [comment]
Hey @andrewmartin,

I just made an example of async server data and opened a PR here -> https://github.com/workco/marvin/pull/47

Imho it is pretty straight forward. Please take a look, and let me know if it works for you. Plan is merge into the master branch at some point.

Cheers!

**Comment by atulmy** [comment]
Implemented similar SSR for React Router v4 using ryanflorence's gist along with React Helmet: https://github.com/atulmy/universal-react/blob/master/src/server/index.js

For each request, you have to create a new store and then reset the store right before sending the response back with initial data to the client.

Also, the container components need to have a `static fetchData` function which essentially loads data asynchronously and are used on server side to get data for hydration.

**Comment by Stanko** [comment]
v1.0.0 includes server rendering including async data on the server 
https://github.com/workco/marvin/pull/65
