### ISSUE TITLE
Add redux-saga

### ISSUE THREAD

**Issue by Stanko** [workco/marvin#24]
Add [redux-saga](﻿https://github.com/redux-saga/redux-saga) for handling Redux actions.

TBD if this should replace `redux-thunk` as a default option, or should we keep both and let user choose.

Related PR: https://github.com/workco/marvin/pull/27

**Comment by madhurgarg71** [comment]
redux-saga is great for keeping your side effects isolated, so I guess keeping only redux-saga is fine.

I don't know if it's a right way of using redux saga or not, but it works for me. I am collecting all the sagas from each view in root saga and then passing root saga into saga middleware.

```javascript
import view1Saga from './views/view1/middleware/saga'
import view2Saga from './views/view2/middleware/saga'
import view3Saga from './views/view3/middleware/saga'

export default function* rootSaga() {
  for(let i=0; i<views.length; i++) {
    for(let saga in views[i]) {
      yield [
        fork(views[i][saga])
      ]
    }
  }
}
```

In your store
```javascript
import rootSaga from './rootSaga'
const sagaMiddleware = createSagaMiddleware()
const middleware = applyMiddleware(sagaMiddleware, logger);
sagaMiddleware.run(rootSaga)
```

Maybe attaching dynamic saga according to view is a good choice? I haven't used it. Here is the issue [https://github.com/redux-saga/redux-saga/issues/76](url)

**Comment by malixsys** [comment]
Please let user choose!
They may prefer thunk, saga, pack, etc...

**Comment by Letladi** [comment]
I vote for saga, then user can replace it if they so desire.

**Comment by Quirksmode** [comment]
Loving this boilerplate, also think saga is a great choice, will work nicely with server async as well. Any idea of when this might be implemented?

**Comment by Stanko** [comment]
It is hard to say, I'm kinda spread too thin atm, hopefully in next month or so.
And I agree sagas are way to go.

**Comment by Stanko** [comment]
https://github.com/workco/marvin/pull/65
