### ISSUE TITLE
devServer for production?

### ISSUE THREAD

**Issue by Piero87** [workco/marvin#34]
Hi,
I have a question about the `devServer` config in webpack.config.js file, why you use it also for production? what is the purpose?

**Comment by Stanko** [comment]
Hello @Piero87,
`webpack.config.js` is used for both dev (`webpack-dev-server`) and building for production (`webpack`). Point of keeping `devServer` config there is to be able to run the app in the production "preview" mode (`npm run preview`). It will run `webpack-dev-server` but with all of the production settings. This way you can test your production build locally.

Cheers!

**Comment by madhurgarg71** [comment]
While running production build ( npm run build), react developer tool shows that the build is not production build?

**Comment by Stanko** [comment]
@Piero87 if you don't mind, I would like to close this issue.

**Comment by Piero87** [comment]
Yes I close it, thanks!
