### ISSUE TITLE
Webpack dashboard wraps incorrectly

### ISSUE THREAD

**Issue by RandomClown0** [workco/marvin#38]
OS: **Windows 10**
Package Version: **0.2.0**
Terminal: **cmd.exe** (using [Git for Windows](https://git-scm.com/download/win), adding unix tools)

Using `npm run client:dev` on Windows cmd, all of the lines wrap incorrectly.

![image](https://user-images.githubusercontent.com/2527631/28863632-9e7a282c-771e-11e7-8e96-a48da7ae35d5.png)

**Comment by Stanko** [comment]
Hello, I mentioned that it has known bugs on windows, for now use marvin without webpack-dashboard.

And as this is bug in the https://github.com/FormidableLabs/webpack-dashboard, and not in our repo, I will close the issue.

Cheers!
