### ISSUE TITLE
SyntaxError on ERROR in ./source/js/views/App/index.jsx

### ISSUE THREAD

**Issue by enricopiovesan** [workco/marvin#39]
Hi, after **npm install** I tried to run **npm start**.

This is the error thought:

```
ERROR in ./source/js/views/App/index.jsx
Module build failed: SyntaxError: Unexpected token (8:19)

   6 |
   7 | export default class App extends Component {
>  8 |   static propTypes = {
     |                    ^
   9 |     children: PropTypes.object,
  10 |   }
  11 |

```

Package: 0.2.0
Node: 8.2.1

**Comment by Stanko** [comment]
Hello @enricopiovesan,
I just tested with the same ndoe version, and it works for me. It seems you are missing `.babelrc` file. Did you download the zip and forgot to copy hidden files (which start with dot) once you unzipped it?

<img width="1360" alt="screenshot 2017-08-02 18 05 00" src="https://user-images.githubusercontent.com/776788/28882970-253ab712-77ad-11e7-9c74-84a3f4447c61.png">

**Comment by enricopiovesan** [comment]
for some reasons **npm install** had overwrite .babelrc like that:

``
/* 
    ./.babelrc
*/  
{
    "presets":[
        "es2015", "react"
    ]
}
``

I just update the file and works fine, sorry 👍
