### ISSUE TITLE
Build not copying images?

### ISSUE THREAD

**Issue by andrewmartin** [workco/marvin#40]
Hi there.

Am loving this boilerplate, great work, thanks for providing it. I was curious, when I'm running `npm run client:build`, it's not copying over images into the `build` directory. I'm struggling with what might be going wrong; any ideas?

**Comment by Stanko** [comment]
Hey @andrewmartin thanks for the kind words.
It should copy the files you imported in your javascript, see [example here](https://github.com/workco/marvin/blob/master/source/js/views/Dashboard/index.jsx#L8). Webpack is a module bundler and only bundles stuff that are imported as modules.

If you still need to copy some images (or any other files) to build folder, there is a great loader:
https://github.com/kevlened/copy-webpack-plugin

Hope that helps!

**Comment by andrewmartin** [comment]
@Stanko 

Ah, sorry! I should have been more clear. So, those imports are working beautifully. I am trying to use CSS background images in my SASS. Any ideas / examples on how to get that working?

What I'm doing now is a little crude, basically:

```
background: #000 url('~/../../assets/img/background-image.png') no-repeat scroll top center;
```

...Then just copying `background-image.png` manually to the `build` directory. Sorry for being a little obtuse on how you've set up the loaders here. I can't use an import in JS for this particular image because I'm setting it on the `<body>`.

**Comment by Stanko** [comment]
You need to use paths relative to your main scss file. Atm you are using `~` in your path to the image. Just replace it with `url(../../relative/path/to/image.png)` and it should work.

**Comment by andrewmartin** [comment]
Yeah, so that’s the tricky thing, I initially tried that, but I hit this error:

```
Failed to compile.

./node_modules/css-loader?{"minimize":false}!./node_modules/postcss-loader/lib?{"sourceMap":true}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true}!./source/scss/app.scss
Module not found: Error: Can't resolve '../../assets/img/background-image.png' in '/Users/andrewmartin/code/marvin/marvin-web/source/scss'
 @ ./node_modules/css-loader?{"minimize":false}!./node_modules/postcss-loader/lib?{"sourceMap":true}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true}!./source/scss/app.scss 6:109755-109794
 @ ./source/scss/app.scss
 @ ./source/js/client.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:3000 webpack/hot/dev-server react-hot-loader/patch ./source/js/client.js
```

Wonder if it’s something with my config? That image does exist at that path on my filesystem.

Thanks either way for your help, I really appreciate it.

**Comment by Stanko** [comment]
If you copy the `body-bg.png` into 
`source/assets/img`

and if you are including it from the 
`source/scss/main.scss` (or any .scss file included in `main.scss`)

your path should be:
`url(../assets/img/body-bg.png)`

firstly `..` goes up to `source` folder and then to `assets/image`

So you don't need `../..` but only `..` once, as files webpack is resolving from `main.scss` and not from `_other-included-file.scss`

Hopefully this will solve it!

**Comment by andrewmartin** [comment]
@Stanko 

You are the man! Thank you, my friend! I was hitting my head against the wall for too long on this one. That makes much more sense! 

Woohoo! Thanks for your time.

**Comment by Stanko** [comment]
You are welcome, glad you got it! 🎉 

I'll make sure to add it to the documentation, so don't close it yet!

**Comment by andrewmartin** [comment]
No problem! Thanks again, wonderful work on this boilerplate. I plan on using it moving forward for all my React projects...really impressive. I love the fact I can choose to "opt in" to universal rendering.

**Comment by Stanko** [comment]
Thank you again! I just updated the readme as well, hopefully it will save some time in the future.

https://github.com/workco/marvin/blob/master/README.md#user-content-importing-images-in-scss
