### ISSUE TITLE
Doc: no "build" script

### ISSUE THREAD

**Issue by lordbah** [workco/marvin#41]
Documentation out-of-date?

https://github.com/workco/marvin#build-client-production
says "npm run build" but there is no "build" script.

In general I don't understand the "x:build" scripts. From the name I would expect them to generate files in the build folder and then return. Instead they do some work and then seem to hang. Somewhere in there it says "webpack is watching the files..." as if it is going to sit around and watch for changes (and not return) - maybe that's what it's doing.

v0.2.0 on Windows 7
I added "set" before the "NODE_ENV=" parts of the various "x:build" scripts because without it Windows told me there was no such command as NODE_ENV.

**Comment by Stanko** [comment]
Hello @lordbah,
My bad, sorry, I did a lot of updates but missed few things in the readme. I just updated it.

For **client** only applications use:

 ```
npm run client:build
```
Read more here: https://github.com/workco/marvin#build-client-production


For **universal** (server+client) applications use:
```
npm run universal:build
```
Read more here: https://github.com/workco/marvin#universal-build-production

Cheers!

**Comment by Stanko** [comment]
I'll consider this resolved.
