### ISSUE TITLE
Redirect after action fired

### ISSUE THREAD

**Issue by kenanchristian** [workco/marvin#42]
I got a login form that dispatches an action that calls an API.
I want to redirect the user to the page before the user sign in (maybe using `router.goBack()`)
How can I do this inside an action? or maybe there's a better way of doing this?

**Comment by Stanko** [comment]
Hello @kenanchristian,
What I usually do is to listen to data changes in `componentWillReceiveProps` in the main view, and then redirect from there.

Something like this:

```js
import React, { Component } from 'react';
import { connect } from 'react-redux';
import { hashHistory } from 'react-router';
import { routeCodes } from '../routes'; // your routess

@connect(state => ({
  user: state.global.user,
}))
export default class SignIn extends Component {
  componentWillReceiveProps(nextProps) {
    const {
      user,
    } = this.props;

    if (!user && nextProps.user) {
      hashHistory.push(routeCodes.HOME);
    }
  }

  render() {
    return (
      <div>
        {/* Your content */}
      </div>
    );
  }
}
```

**Comment by kenanchristian** [comment]
Hey @Stanko It works like a charm!
Thanks a lot 👍
