### ISSUE TITLE
Warning: Failed prop type: Invalid prop `asyncData` of type `object` supplied to `Dashboard`, expected `string`

### ISSUE THREAD

**Issue by davidhibbard1** [workco/marvin#44]
This only happens on first click of async button on dashboard

**Comment by Stanko** [comment]
Hello @davidhibbard1,
This is a simple `PropTypes` error, I will resolve it today. Sorry for the late response!

**Comment by Stanko** [comment]
Fixed here: https://github.com/workco/marvin/commit/e7fe98190e598e2f112b8e12a0398350beb1e7be#diff-c2a772da0f18eeb36f7ce4b584878afdR18
