### ISSUE TITLE
PWA Name

### ISSUE THREAD

**Issue by kenanchristian** [workco/marvin#45]
I just noticed that with this build, the web app can also be used for Progressive Web App (PWA)
The problem is, the app name is `Webpack App`. Is there a way to change this?

**Comment by Stanko** [comment]
Hello @kenanchristian,
Sorry for the late response.

I'm pretty sure you need to use PWA manifest (check MDN documentation https://developer.mozilla.org/en-US/docs/Web/Manifest) to add PWA meta data.

If that helps, please close issue as resolved, thanks!

**Comment by kenanchristian** [comment]
@Stanko Turns out it can be easily changed using a `meta` tag inside the html head. Thanks for the tip! 👍
