### ISSUE TITLE
Build not including sass file

### ISSUE THREAD

**Issue by kenanchristian** [workco/marvin#46]
Hey I've been using your new version of marvin and it works great, except for one problem.
It include all the sass file when on dev but not on build.

This is how my folder structure looks like
![image](https://user-images.githubusercontent.com/11202498/30074473-dc8dc22a-929b-11e7-8737-5398582fb0a0.png)
I only change `scss` to `sass`
![image](https://user-images.githubusercontent.com/11202498/30074484-e6cca260-929b-11e7-9b35-e9a871193b28.png)
Then import it to the `client.js` file
The `app.sass` only have 2 lines which imports from the index file of the subfolders
![image](https://user-images.githubusercontent.com/11202498/30074682-970af708-929c-11e7-92e8-b09f9dd5c3d0.png)

**Comment by Stanko** [comment]
Hello @kenanchristian,

By what you described it shouldn't work in dev either 😄 

Anyway, webpack is set to handle `.scss` files, but not `.sass`

You need to change it in two places:
https://github.com/workco/marvin/blob/master/webpack/config.js#L155
https://github.com/workco/marvin/blob/master/webpack/config.js#L163

```js
// change
scss

// to 
(scss|sass) // or only sass if you don't need scss
```

Cheers!

**Comment by kenanchristian** [comment]
@Stanko Sorry I forgot to reply here, eventually I modified the webpack config a bit to add support for both css and sass/scss files by adding another ExtractTextPlugin. Just tell me if you want me to add pull request, maybe I can help out.

Cheers! 🍺 👍
