### ISSUE TITLE
Had error

### ISSUE THREAD

**Issue by DastanSE** [workco/marvin#48]
```
404s will fallback to /index.html
Time: 5904ms
           Asset     Size  Chunks  Chunk Names
client/client.js  2.54 kB       0  main
client/vendor.js  1.98 MB       1  vendor

ERROR in ./source/js/client.js
Module build failed: SyntaxError: Unexpected token (22:4)

  20 | const render = Component => {
  21 |   ReactDOM.render(
> 22 |     <AppContainer>
     |     ^
  23 |       <Provider store={ store }>
  24 |         <Component />
  25 |       </Provider>

 @ multi (webpack)-dev-server/client?http://0.0.0.0:3000 webpack/hot/dev-server react-hot-loader/patch ./source/js/client.js
webpack: Failed to compile.``
```

**Comment by Stanko** [comment]
Hello @DastanSE,
Do you have `.babelrc` file - https://github.com/workco/marvin/blob/master/.babelrc ?

It seems that you downloaded zip, extracted it and forgot hidden (dot) files.

If that doesn't help please provide me with some more info, which node version are you using and which command did you run?

**Comment by DastanSE** [comment]
it was this problem, but i cloned your repository, not downloaded

**Comment by DastanSE** [comment]
thank you very much for quick answer!!

**Comment by ddaaggeett** [comment]
@DastanSE 

the `.babelrc` file comes with the clone

i ran into some trouble while copying files around with the file explorer. in you're in ubuntu, or something similar, perhaps you forgot to copy the invisible files too? if that's the case, don't forget the `.gitignore` file either.
