### ISSUE TITLE
ReferenceError: Can't find variable: SockJS

### ISSUE THREAD

**Issue by nikitajain7007** [workco/marvin#54]
This issue is appearing in Safari macOS Sierra . Can this be fixed any time soon or is there any alternative
![screen shot 2017-10-16 at 8 24 15 pm](https://user-images.githubusercontent.com/22912869/31618433-8cc1a110-b2af-11e7-9bc3-c9b0f4343bfe.png)

**Comment by Stanko** [comment]
I'm on Sierra myself, and as you can see it is working fine. It seems it is something with your local setup. Can you check if there is any problems in the terminal? Have you forgot to run `npm install` after adding new packages? It is really hard to debug it with only the screenshot you posted.

![screenshot 2017-10-16 17 54 27](https://user-images.githubusercontent.com/776788/31621855-18dc8a6c-b29b-11e7-8667-d63e05640ef7.png)

**Comment by nikitajain7007** [comment]
Steps I followed
Git clone
Npm install
Npm start 

Works fine on Chrome, but when u open the host on safari , it is throwing this error

**Comment by nikitajain7007** [comment]
No issue is reported on terminal

**Comment by Stanko** [comment]
That definitely sounds like a issue on your local safari. Try to run it with addons disabled.

**Comment by nikitajain7007** [comment]
Hey... Cleared cache, and there is no add on's added in safari - attaching screen shot . Is there anything else that I should try ?
![screen shot 2017-10-17 at 12 21 53 pm](https://user-images.githubusercontent.com/22912869/31650800-aa714bde-b336-11e7-8515-2ab6087717fe.png)

**Comment by nikitajain7007** [comment]
works perfectly fine on chrome . Attaching screen shot
![screen shot 2017-10-17 at 12 33 36 pm](https://user-images.githubusercontent.com/22912869/31650867-f1c9e112-b336-11e7-9d52-14ab0bc6c580.png)

**Comment by nikitajain7007** [comment]
I think this issue is with respect to safari version. My safari version is 10.1.2 . On google , I found that if we upgrade the version this issue will be resolved. (Tried with safari 11 and its working fine there )
But I am looking for something that can support safari 10x versions as well. Can I get some help here please.

**Comment by Stanko** [comment]
Well the problem is `webpack.config.js`

Just replace the devtool from:
```
devtool: IS_PRODUCTION ? false : 'cheap-eval-source-map',
```

to:
```
devtool: IS_PRODUCTION ? false : 'source-map',
```

It seems that older safaris don't support `cheap-eval-source-map` but prodcution build works, you can try `npm run client:preview`.

Cheers!

**Comment by nikitajain7007** [comment]
Thank you !! it worked
