### ISSUE TITLE
Dynamic `<head>` tag

### ISSUE THREAD

**Issue by kenanchristian** [workco/marvin#56]
Is there a recommended way of adding a dynamic content to the `<head>` tag?

**Comment by Stanko** [comment]
Hey, I would suggest using https://github.com/nfl/react-helmet

**Comment by kenanchristian** [comment]
@Stanko Yeah, it works on static `meta` tags. But to add a dynamic one, the react app need to be converted to SSR for the `Open Graph` to work, do you know a workaround for this instead of converting to SSR?

**Comment by Stanko** [comment]
If you want to use dynamic data returned from the server, you need to have actual web server serving it. (Too much "servers" in one sentence 😃.) You don't have to convert it to SSR for this, but you need a server like express or apache.

You can setup express which will return `index.html` with dynamic metadata and links to js app, everything else stays the same.

Hope that helps.

**Comment by kenanchristian** [comment]
@Stanko Thanks! just tried it with express, and it works amazing! 😃  👍
