### ISSUE TITLE
Missing process.env.PORT when deploying to heroku

### ISSUE THREAD

**Issue by Zelltron** [workco/marvin#61]
I'm trying to deploy this repo to heroku, but I'm having trouble configuring the production server to comply with heroku's dynamically generated ports. For some reason when I look up the PORT variable in the webpack/config.js file the process is returning undefined and defaulting to 3000. I'm relatively new to webpack, so I feel like I'm missing something obvious. I have a repo open here --> [NullVoid]( https://github.com/Zelltron/nullvoid)

package.json
![package.json](https://user-images.githubusercontent.com/8294092/32610766-c1110fac-c531-11e7-9e6c-afb963d1df87.png)
webpack/config.js
![webpack/config.js](https://user-images.githubusercontent.com/8294092/32610813-d9be5c08-c531-11e7-9e68-5bc435b267ec.png)
source/js/server.js
![source/js/server.js](https://user-images.githubusercontent.com/8294092/32610868-08eeceae-c532-11e7-8dc1-6263db24e85a.png)

**Comment by Zelltron** [comment]
Got it! My build order was wrong.

![image](https://user-images.githubusercontent.com/8294092/32612448-5d33b2dc-c536-11e7-85bb-ef2701fa7f4d.png)

**Comment by Stanko** [comment]
Glad it worked! 🎉
