### ISSUE TITLE
[ASK ]Can i use external js and css with Marvin ?

### ISSUE THREAD

**Issue by Rockies07** [workco/marvin#64]
Hii, i wonder if i can use external asset such as css and js extension
cuz my web is taken from web templete that have so many css and js files

when i run `yarn client:build` css and js assets is not included in build directory
so i wonder how, or is it still possible in marvin?

the last thing that i try is included css and js in index.html
like `<link rel="stylesheet" type="text/css" href="/assets/style/fluid-grid-1474473600.css" />`
and `<script type="text/javascript" src="/assets/js/common.min-1394346652.js"></script>`

thankyou

**Comment by Stanko** [comment]
I'm not sure what are you trying to achieve, but to automatically include JS or CSS files you need to import them as webpack modules.

**Comment by frengkys** [comment]
![image](https://user-images.githubusercontent.com/20334470/33302877-d4fe4b06-d431-11e7-851c-57e642692f5b.png)
hiii @Stanko ,
i wanna convert website from none react app to react app...
when i run `yarn start` web is run smoothly but when i run `yarn client:build` the asset directory not extracted in build directory...

i am newbie in react app

**Comment by Stanko** [comment]
As I said, you need to import your assets as webpack modules. If you are not familiar with webpack, setting up react project might be really hard. I recommend you to start learning more about webpack:

* Official documentation - https://webpack.js.org/guides/getting-started/
* Free online course - https://www.udemy.com/learn-webpack-2-from-scratch/
