### ISSUE TITLE
Capitalization mismatch for directory "components/Global/"

### ISSUE THREAD

**Issue by RandomClown0** [workco/marvin#67]
marvin version: **1.0.0**  
OS: **Ubuntu**  

I ran it on my Linux box & it crashed. It couldn't find **components/global**, because it's named **components/Global**.

The fix is to rename the directory from **components/Global/** to lowercase (or would you prefer to capitalize the import statement?)

Crash log:
```
ERROR in ./source/js/views/App.jsx
Module not found: Error: Can't resolve 'components/global/Menu' in '/var/www/cts/react-dashboard/source/js/views'
 @ ./source/js/views/App.jsx 15:0-42
 @ ./source/js/client.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 webpack/hot/dev-server babel-polyfill ./source/js/client.js
```

**Comment by Stanko** [comment]
Sorry about that, I did rename it, but as OSX is case insensitive by default, git didn't pick the change up. 

Fixed https://github.com/workco/marvin/commit/7d70517c22b5f21c34e56a2c88b664bd118623e2
