### ISSUE TITLE
run dev error

### ISSUE THREAD

**Issue by Terrycoco** [workco/marvin#68]
I setup as instructed.  When I run npm start, it runs but I get the following errors in the console.
```
sw.js:1 Uncaught (in promise) TypeError: Failed to fetch
Promise rejected (async)
fetchListener @ sw.js:1
sockjs.js?be2c:1601 GET http://localhost:8080/sockjs-node/info?t=1516752439544 net::ERR_FAILED
```

**Comment by Stanko** [comment]
Hello @Terrycoco,
Please when you open an issue, try to give more information. Browser, os and node versions can give more information. Copying the whole error stack help as well.

Anyway this seems that you have fetch request that fails and is missing a `catch`. Marvin uses fetch in it's API wrapper only, and it includes error catching. So if you added fetch request somewhere you might want to add error handling to it.

Hope that helps!
