### ISSUE TITLE
backporting changes from fork

### ISSUE THREAD

**Issue by basti1253** [workco/marvin#7]
Hey Stanko,

instead of opening a PR with all changes I decided to open this issue here first. Sorry for the delay I was hardly hit by a cold.
Can you take a look at my changes so you may easier decide what you want to have merged upstream?
Here's a quick comparison link https://github.com/Stanko/react-redux-webpack2-boilerplate/compare/master...basti1253:master

What's inside:
- HMR working (withouth react hot loader)
- sassy source maps
- react-actions and redux-promise middleware
- dropped webpack dashboard in favor of minimal devsever output
- normalize-scss import from node-modules
- browserslist (package.json)
- dropped legacy decorators
- cross-env in npm scripts
- redux devtools: use browser plugin instead (only if available)
- using pure components
- changed directory structure
- dropped class method bindings in constructors in favor of arrow functions
- removed prepush hooks as I don't need it

Please let me know what subsets/features you want upstream and I prepare a PR.

best regards

Sebastian

**Comment by Stanko** [comment]
Woah, this is huge mate! Please give me few days to go through it.

Thank you so much for the effort!
