### ISSUE TITLE
how to configure debug on marvin

### ISSUE THREAD

**Issue by luizhenriquesoares** [workco/marvin#87]
how to configure debug in vs code. what settings should I set to start marvin with debug, I'm using the debbuger for chrome plugin.

my settings:
```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "chrome",
      "request": "launch",
      "name": "Launch Chrome against localhost",
      "url": "http://localhost:8082",
      "webRoot": "${workspaceFolder}/client",
      "sourceMaps": true,
      
    }
  ]
}
```

**Comment by Stanko** [comment]
Hello @luizhenriquesoares,
Unfortunately I've never used vscode debug.
But if you manage to solve it, please post it here, it might be helpful to other people too.

Cheers!

**Comment by luizhenriquesoares** [comment]
Ok Stanko... How do you debug?

**Comment by Stanko** [comment]
Well that is rather generic question, but I'll do my best.

For client javascript apps I'm using Chrome for development and it's excellent javascript debugger and developer tools. This applies to React apps as well. 

For React/Redux apps there are two really helpful extensions:

* React Dev Tools - https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi?hl=en (this one works out-of-the-box)
* Redux Dev Tools - https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd (Marvin automatically connects to this one)

As for the nodejs server apps, I'm not that experienced, but I'm using combination of [node's debugger](https://nodejs.org/api/debugger.html) and `console.logs`. 

Hope that helps, cheers!


P.S. I think what you are trying to do isn't working as there is webpack which transpiles application code. You might want to look at one of these (I just googled them up, as I'm not using vscode, I can't be sure if they are working, but it is worth giving it a try): 

* https://stackoverflow.com/questions/48982555/how-do-i-debug-webpack-dev-servers-built-in-express-server-in-vs-code
* https://stackoverflow.com/questions/46438471/how-to-use-vs-code-debugger-with-webpack-dev-server-breakpoints-ignored
* https://github.com/kube/vscode-ts-webpack-node-debug-example
