### ISSUE TITLE
not getting data from cache in safari

### ISSUE THREAD

**Issue by raj16559** [workco/marvin#88]
Every time saga is sending new request to server to get data in safari(v11.1.1)

**Comment by Stanko** [comment]
Hello @raj16559,
 I've tried both `client:dev` and `universal:dev` and both tasks work as expected (Safar 11.1.1 (13605.2.8) and Marvin 1.1.0). Of course server is sending requests every time, and that's something you need to solve by adding a server cache level.

Other thing that comes to my mind that you are using from saga helpers, take a look at`getEvery` and `getLatest` [in the official documentation](https://redux-saga.js.org/docs/basics/UsingSagaHelpers.html).

You didn't really describe your problem, so I'm not sure what are you trying to do. Anyway this is not problem with Marvin but something with your implementation.

Hope that helps, cheers!
