### ISSUE TITLE
Component data are flickering on every click on sidebar menu & when state change in safari 11.1.1 (React JS)

### ISSUE THREAD

**Issue by dipeshmali** [workco/marvin#89]
I am using react saga mavin boilerplate and i am facing an issue  whenever i click on menu at left sidebar each an every time images & data are flickering in (safari 1.11.1).
this issue is only occur in safari but its working fine in chrome & firefox. i am not actually understand what is happening , when i open network in safari each an every time images are loaded in cache after removing cache images its again re-generate images but not in chrome & firefox.
please help me to solve this problem. Thanks in advance
please take a look the video link below:
1)https://tinytake.s3.amazonaws.com/pulse/dhp-gmail/attachments/8192300/TinyTake02-07-2018-02-55-12.mp4
2)https://tinytake.s3.amazonaws.com/pulse/dhp-gmail/attachments/8192648/TinyTake02-07-2018-03-49-26.mp4

**Comment by Stanko** [comment]
Hello @dipeshmali,
This seems like a React `key` issue https://reactjs.org/docs/lists-and-keys.html
As this is not Marvin issue, I can't help you much.
Cheers!

**Comment by dipeshmali** [comment]
I would like to thank you @Stanko sir for helping me there was key issue while rendering records and finally i got the solution by passing unique key for each record.
